version: '3.3'

services:
  nginx: 
    image: nginx:latest
    container_name: production_nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    expose:
      - "6379"

  db:
    container_name: db
    build: ./db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress_1
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress_1:
    container_name: wordpress_1
    depends_on:
      - db
    image: wordpress:latest
    expose:
      - "80"
    restart: always
    volumes:
      - ./html/wordpress_1:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress_1

  wordpress_2:
    container_name: wordpress_2
    depends_on:
      - db
    image: wordpress:latest
    expose:
      - "80"
    restart: always
    volumes:
      - ./html/wordpress_2:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress_2

volumes:
    db_data: {}
